[package]
name = "siwe_signer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
hex = "0.4.3"
ic-cdk = "0.11.4"
ic-cdk-macros = "0.7.1"
siwe = { git = "https://github.com/domwoe/siwe-rs" }
time = { version = "0.3.20", default-features = false }
